### ISSUE TITLE
PackageManager$NameNotFoundException 

### ISSUE THREAD

**Issue by 75py** [75py/Aplin#15]
Aplin 2.2.0
Nexus 7 (2012)
5.0.0

```
Fatal Exception: android.content.pm.PackageManager$NameNotFoundException: com.google.android.apps.docs.editors.sheets
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:114)
       at com.nagopy.android.aplin.model.converter.AppParameters$firstInstallTime.setValue(AppParameters.kt:47)
       at com.nagopy.android.aplin.model.converter.AppConverter.setValues(AppConverter.kt:39)
       at com.nagopy.android.aplin.model.Applications$refresh$$inlined$use$lambda$1.execute(Applications.kt:64)
       at io.realm.Realm.executeTransaction(Realm.java:1016)
       at com.nagopy.android.aplin.model.Applications.refresh(Applications.kt:54)
       at com.nagopy.android.aplin.model.Applications$initialize$1.run(Applications.kt:37)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by 75py** [comment]
再現しないのでクローズ。
発生次第またissueに登録する。
