### ISSUE TITLE
TableView.java line null

### ISSUE THREAD

**Issue by 75py** [75py/Aplin#68]
#### in io.realm.internal.TableView.nativeGetSourceRowIndex

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/5683b67df5d3a7f76bbe0c58](https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/5683b67df5d3a7f76bbe0c58)

**Comment by 75py** [comment]
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: rowIndex is less than 0.
       at io.realm.internal.TableView.nativeGetSourceRowIndex(TableView.java)
       at io.realm.internal.TableView.getSourceRowIndex(TableView.java:127)
       at io.realm.RealmResults.get(RealmResults.java:168)
       at com.nagopy.android.aplin.presenter.AppListPresenter$onCreateViewHolder$1.onClick(AppListPresenter.kt:107)
       at android.view.View.performClick(View.java:4861)
       at android.view.View$PerformClick.run(View.java:19980)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by 75py** [comment]
モンキーテストで稀に再現する。
```
adb shell monkey -p com.nagopy.android.aplin -v 5000
```
原因はよくわからないが、とりあえず強制終了はしないように対応する。
ログ出力も仕込む。
