### ISSUE TITLE
AppConverter.kt line 82

### ISSUE THREAD

**Issue by 75py** [75py/Aplin#69]
#### in com.nagopy.android.aplin.model.converter.AppConverter.prepare

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/568420a4f5d3a7f76bc02275](https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/568420a4f5d3a7f76bc02275)

**Comment by 75py** [comment]
```
Fatal Exception: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by rx.exceptions.OnErrorNotImplementedException: Package manager has died
       at rx.Observable$27.onError(Observable.java:7996)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:575)
       at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:561)
       at com.nagopy.android.aplin.model.converter.AppConverter.prepare(AppConverter.kt:82)
       at com.nagopy.android.aplin.model.converter.AppConverter.setValues(AppConverter.kt:53)
       at com.nagopy.android.aplin.model.Applications$refresh$$inlined$use$lambda$1.execute(Applications.kt:83)
       at io.realm.Realm.executeTransaction(Realm.java:1055)
       at com.nagopy.android.aplin.model.Applications.refresh(Applications.kt:73)
       at com.nagopy.android.aplin.model.Applications$$special$$inlined$apply$lambda$1.call(Applications.kt:50)
       at com.nagopy.android.aplin.model.Applications$$special$$inlined$apply$lambda$1.call(Applications.kt:48)
       at rx.Observable.unsafeSubscribe(Observable.java:8171)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.os.TransactionTooLargeException
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:496)
       at android.content.pm.IPackageManager$Stub$Proxy.queryIntentActivities(IPackageManager.java:2593)
       at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:569)
       at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:561)
       at com.nagopy.android.aplin.model.converter.AppConverter.prepare(AppConverter.kt:82)
       at com.nagopy.android.aplin.model.converter.AppConverter.setValues(AppConverter.kt:53)
       at com.nagopy.android.aplin.model.Applications$refresh$$inlined$use$lambda$1.execute(Applications.kt:83)
       at io.realm.Realm.executeTransaction(Realm.java:1055)
       at com.nagopy.android.aplin.model.Applications.refresh(Applications.kt:73)
       at com.nagopy.android.aplin.model.Applications$$special$$inlined$apply$lambda$1.call(Applications.kt:50)
       at com.nagopy.android.aplin.model.Applications$$special$$inlined$apply$lambda$1.call(Applications.kt:48)
       at rx.Observable.unsafeSubscribe(Observable.java:8171)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by 75py** [comment]
アプリが多すぎるっぽい？
要調査。
