### ISSUE TITLE
UncheckedRow.java line null

### ISSUE THREAD

**Issue by 75py** [75py/Aplin#70]
#### in io.realm.internal.UncheckedRow.nativeSetString
- Number of crashes: 1
- Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/56909ca5f5d3a7f76bf4534f](https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/56909ca5f5d3a7f76bf4534f)

**Comment by 75py** [comment]
```
Fatal Exception: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5430)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
Caused by rx.exceptions.OnErrorNotImplementedException: Unrecoverable error. Failure when converting to UTF-8; error_code = 5;  0xec72 0x0047 0x000d 0x0122 0x0031 0x0078 0x0054 0xa7d6 0x7200 0x0071 0x0523 0x000f 0x002b 0x2427 0x0041 0x0061 0x94a5 0x01d6 0xc96a 0xaa6e 0x009b 0x000a 0x0009 0x003a 0x0068 0xdc9b 0x06c8 0x06c7 0x0512 0x0029 0x6845 0x031b 0x01ad 0x001c 0x0082 0x0075 0x0037 0x0017 0x8648 0xee0d 0x0429 0x0026 0x0021 0xf3d3 0x8735 0x06de 0x006b 0x0035 0x0009 0x0043 0x0044 0x0007 0x0026 0x6d52 0x97f8 0x0003 0x1884 0x0070 0x0068 0x89f3 0x2aa9 0xa6de 0x0012 0x0038 0xe291 0x0309 0x003c 0xf089 0x003a 0x02a3 0x8c0f 0x0014 0x0031 0x0006 0x0740 0x2e53 0x0033 0x0010 0x0009 0x007e 0x0039 0x07bf 0x0006 0x041c 0x0269 0x02b8 0x85c5 0x5e5c 0xad79 0x0440 0x0047 0x0010 0xd096 0x0035 0x7a54 0xf5c1 0x006e 0x004d 0x0698 0x002e 0x002e 0x05a1 0x0049 0x11b2 in io_realm_internal_UncheckedRow.cpp line 298
       at rx.Observable$27.onError(Observable.java:7996)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5430)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
Caused by io.realm.exceptions.RealmError: Unrecoverable error. Failure when converting to UTF-8; error_code = 5;  0xec72 0x0047 0x000d 0x0122 0x0031 0x0078 0x0054 0xa7d6 0x7200 0x0071 0x0523 0x000f 0x002b 0x2427 0x0041 0x0061 0x94a5 0x01d6 0xc96a 0xaa6e 0x009b 0x000a 0x0009 0x003a 0x0068 0xdc9b 0x06c8 0x06c7 0x0512 0x0029 0x6845 0x031b 0x01ad 0x001c 0x0082 0x0075 0x0037 0x0017 0x8648 0xee0d 0x0429 0x0026 0x0021 0xf3d3 0x8735 0x06de 0x006b 0x0035 0x0009 0x0043 0x0044 0x0007 0x0026 0x6d52 0x97f8 0x0003 0x1884 0x0070 0x0068 0x89f3 0x2aa9 0xa6de 0x0012 0x0038 0xe291 0x0309 0x003c 0xf089 0x003a 0x02a3 0x8c0f 0x0014 0x0031 0x0006 0x0740 0x2e53 0x0033 0x0010 0x0009 0x007e 0x0039 0x07bf 0x0006 0x041c 0x0269 0x02b8 0x85c5 0x5e5c 0xad79 0x0440 0x0047 0x0010 0xd096 0x0035 0x7a54 0xf5c1 0x006e 0x004d 0x0698 0x002e 0x002e 0x05a1 0x0049 0x11b2 in io_realm_internal_UncheckedRow.cpp line 298
       at io.realm.internal.UncheckedRow.nativeSetString(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.setString(UncheckedRow.java:244)
       at io.realm.AppRealmProxy.setLabel(AppRealmProxy.java:161)
       at com.nagopy.android.aplin.model.converter.AppParameters$label.setValue(AppParameters.kt:39)
       at com.nagopy.android.aplin.model.converter.AppConverter.setValues(AppConverter.kt:57)
       at com.nagopy.android.aplin.model.Applications$refresh$$inlined$use$lambda$1.execute(Applications.kt:83)
       at io.realm.Realm.executeTransaction(Realm.java:1055)
       at com.nagopy.android.aplin.model.Applications.refresh(Applications.kt:73)
       at com.nagopy.android.aplin.model.Applications$$special$$inlined$apply$lambda$1.call(Applications.kt:50)
       at com.nagopy.android.aplin.model.Applications$$special$$inlined$apply$lambda$1.call(Applications.kt:48)
       at rx.Observable.unsafeSubscribe(Observable.java:8171)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by 75py** [comment]
よくわからないので、try-catchで囲ってログを仕込む（1.1.1）。

**Comment by 75py** [comment]
このエラーと一緒に Error occurred. pkg=〜 のメッセージが出たら、おそらくそのアプリが原因。
エラーレポートがくるまでは保留で。

**Comment by 75py** [comment]
3.1.0で Realm をやめたので、今後は発生しない。
