### ISSUE TITLE
SharedGroup.java line null

### ISSUE THREAD

**Issue by 75py** [75py/Aplin#93]
#### in io.realm.internal.SharedGroup.createNativeWithImplicitTransactions

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/569b8691f5d3a7f76b24503c](https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/569b8691f5d3a7f76b24503c)

**Comment by 75py** [comment]
```
Non-fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:67)
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:47)
       at io.realm.BaseRealm.<init>(BaseRealm.java:76)
       at io.realm.Realm.<init>(Realm.java:126)
       at io.realm.Realm.createAndValidate(Realm.java:246)
       at io.realm.Realm.createInstance(Realm.java:231)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getDefaultInstance(Realm.java:181)
       at com.nagopy.android.aplin.model.Applications$updateDefaultAppStatus$1.call(Applications.kt:192)
       at com.nagopy.android.aplin.model.Applications$updateDefaultAppStatus$1.call(Applications.kt:190)
       at rx.Observable.unsafeSubscribe(Observable.java:8171)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by 75py** [comment]
updateDefaultAppStatus のトランザクション単位が大きすぎ。今の実装だと、一件でも例外になると全部ロールバックする気が。
トランザクションを一アプリずつにしたほうが良さそう。

**Comment by 75py** [comment]
一部端末・ユーザーでしか起きていないようなのでクローズ。今後も発生するようなら再度検討する。
トランザクション単位は修正済み。 #94
