### ISSUE TITLE
SharedGroup.java line null

### ISSUE THREAD

**Issue by 75py** [75py/Aplin#94]
#### in io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/569b8691f5d3a7f76b24503e](https://fabric.io/75pys-projects/android/apps/com.nagopy.android.aplin/issues/569b8691f5d3a7f76b24503e)

**Comment by 75py** [comment]
```
Non-fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188
       at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(SharedGroup.java)
       at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:99)
       at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:60)
       at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:116)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:292)
       at io.realm.Realm.commitTransaction(Realm.java:108)
       at io.realm.Realm.executeTransaction(Realm.java:1056)
       at com.nagopy.android.aplin.model.Applications$updateDefaultAppStatus$1.call(Applications.kt:194)
       at com.nagopy.android.aplin.model.Applications$updateDefaultAppStatus$1.call(Applications.kt:190)
       at rx.Observable.unsafeSubscribe(Observable.java:8171)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by 75py** [comment]
一部端末でしか起きていないようなのでクローズ。今後も発生するようなら再度検討する。
